"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { AlertsProvider } from "../contexts/AlertsContexts";
import { LeafletMapProvider } from "../contexts/LeafletMapContext";

// https://mui.com/material-ui/customization/dark-mode/
const theme = createTheme({
  colorSchemes: {
    dark: true,
  },
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// NOT ALLOWED IN "use client"
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={theme}>
          <AlertsProvider>
            <LeafletMapProvider>
              {children}
            </LeafletMapProvider>
          </AlertsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
